# Copyright (C) 2023 Dynamic Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Sync Github and Jira release

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  create-jira-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: Find fixed issues
        run: |
          PROJECT_NAME="KYAN"
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: ${LATEST_TAG}"
          
          PREVIOUS_TAG=$(git describe --abbrev=0 ${LATEST_TAG}^)
          echo "Previous tag: ${PREVIOUS_TAG}"
          
          COMMITS=$(git log ${PREVIOUS_TAG}..${LATEST_TAG} --pretty=format:"%s" | grep ${PROJECT_NAME})
          TICKETS=$(echo "${COMMITS}" | grep -o '${PROJECT_NAME}\-[0-9]\+' | sort -u | paste -sd "," -)
          echo "Tickets found in commit messages: ${TICKETS}"
          
          echo "RELEASE_NAME=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "TICKETS=${TICKETS}" >> $GITHUB_ENV
          if [ -z "${TICKETS}" ]; then
            echo "HAS_TICKETS=false" >> $GITHUB_ENV
            echo "No tickets found. JIRA release won't be created."
          else
            echo "HAS_TICKETS=true" >> $GITHUB_ENV
          fi

      - name: create release
        if: ${{ env.HAS_TICKETS == 'true' }}
        uses: armona/jira-release-actions@v2.0.6
        with:
          create: true
          email: ${{ secrets.ATLASSIAN_CLOUD_USER }}
          api_token: ${{ secrets.ATLASSIAN_CLOUD_APIKEY }}
          subdomain: ${{ secrets.ATLASSIAN_CLOUD_DOMAIN }}
          jira_project: 10233
          tickets: ${{ env.TICKETS }}
          release_name: ${{ env.RELEASE_NAME }}